FROM --platform=linux/amd64 node:16-slim

WORKDIR /app

COPY package*.json ./
COPY server.js ./

RUN npm install

COPY backend ./backend

# Cloud Run固有の環境変数を設定
ENV NODE_ENV=production
ENV API_HOST=appgenius-portal-backend-235426778039.asia-northeast1.run.app

# ポートの設定
ENV PORT=8080
EXPOSE 8080

# 起動コマンド
CMD ["node", "server.js"]
